### ISSUE TITLE
Skip serialization if value equals default

### ISSUE THREAD

**Issue by adrientetar** [Tinche/cattrs#19]
Consider a class like this:

```python
@attr.s(slots=True)
class Point(object):
    x: int = attr.ib()
    y: int = attr.ib()
    type: Optional[str] = attr.ib(default=None)
```

It would be nice if the `type` attribute doesn't get serialized when its value is the default value. Is that possible with the current cattrs?

**Comment by Tinche** [comment]
Hi,

I don't think it's possible out of the box. What you could do is subclass `cattr.Converter` and override `unstructure_attrs_asdict` with your own code, which would add the check. It should be quite simple, report back if you need help :)

**Comment by bluetech** [comment]
Your suggestion would break compatibility.

Consider two servers, A and B, using cattrs-serialized class to communicate. A sends data to B. Suppose the class is changed to use a different default value for attribute X. Suppose server A is updated, but server B not yet. Suppose A serializes an instance which uses the default value for X.

Without your suggestion, changing the default value is fine -- the sides will agree on the value, since A serializes the value it is using, and B will use that.

With your suggestion, the sides will disagree -- B will use the old default value.

**Comment by Tinche** [comment]
I think it's a legitimate use case, just that it should be opt-in.

For example, at work we're considering generating client classes (C#) directly from our Python attrs classes. Then the defaults would always match up and not sending the default values would just be more efficient.

**Comment by adrientetar** [comment]
> Suppose server A is updated, but server B not yet.

Changing communication protocols only on one side breaks, yes.

> not sending the default values would just be more efficient.

Also reduces file size or unnecessary data when writing to a file.

**Comment by bluetech** [comment]
> I think it's a legitimate use case, just that it should be opt-in.

Agreed. The behavior can be useful, so an opt-in will be useful.

> Changing communication protocols only on one side breaks, yes.

Just noting, it's not important just for spatial communication (e.g. two servers) but also temporal (e.g. save file). It's always possible that between the time you write the save file and the time you read it, the default will change.

Formats which have the omit-default behavior are usually designed for it, e.g.:

- The default values are predefined for each data type, and cannot change between protocol versions, e.g. [protobuf](https://developers.google.com/protocol-buffers/docs/proto3#default). In attrs the default value can change.

- [Dubious] There is an explicit "not set"/"use default" state. In attrs the default is assigned in `__init__` and there is no way to know if it was assigned explicitly or the default.

**Comment by petergaultney** [comment]
I would like to see this as an option as well. 

There is an extremely simple, two line implementation for attrs classes, though it would require extra work to make a configurable property. Not sure whether this should be configurable per Converter, or configurable per attrs type, or what. Perhaps both?

**Comment by petergaultney** [comment]
following up on this much later:

there's also a way to hack this into `cattrs` without inheritance, if you don't have the option to define your own converter. This is because `cattrs` already does dynamic dispatch of all unstructure calls via its MultiStrategyDispatch.

You can hook into the FunctionDispatch strategy to handle all cases that satisfy `_is_attrs_class` without requiring inheritance at all. 

My approach is a little bit 'fancy' so that I can configure this per-type. And my approach doesn't attempt to handle the AS_TUPLE `UnstructureStrategy`. 

```
import typing as ty

from cattr import Converter, UnstructureStrategy
from cattr.converters import _is_attrs_class


class AttrsStripDefaultsUnstructurePatch:
    def __init__(self, converter: Converter):
        """If you create this, you will be performing a monkey patch on your converter.

        However, the patch will only activate for classes that have been
        explicitly registered.
        """
        self.registry: ty.Set[ty.Type] = set()
        if converter.unstruct_strat != UnstructureStrategy.AS_DICT:
            raise ValueError('This patch does not work with the AS_TUPLE unstructure strategy')

        self.original_method = converter._unstructure_attrs
        new_pairs = [
            (can_handle, handler)
            if can_handle != _is_attrs_class else
            (can_handle, self)
            for can_handle, handler in converter._unstructure_func._function_dispatch._handler_pairs
        ]
        converter._unstructure_func._function_dispatch._handler_pairs = new_pairs
        converter._unstructure_func._function_dispatch.dispatch.cache_clear()

    def register(self, _type: ty.Type):
        self.registry.add(_type)

    def __call__(self, obj_to_unstructure: ty.Any) -> ty.Dict[str, ty.Any]:
        """The input argument may technically be Any but cattrs guarantees it is an attrs class"""
        rv = self.original_method(obj_to_unstructure)
        attrs_type = obj_to_unstructure.__class__
        if attrs_type in self.registry:
            rv = strip_attr_defaults(attrs_type, rv)
        return rv


# a utility function
def strip_attr_defaults(attrs_type: ty.Type, m: ty.Mapping[str, ty.Any]) -> ty.Dict[str, ty.Any]:
   attr_defaults_by_name = {attr.name: attr.default for attr in attrs_type.__attrs_attrs__}
    return {
        k: v
        for k, v in m.items()
        if k not in attr_defaults_by_name or v != attr_defaults_by_name[k]
    }
```

As you can see, the actual work to strip the defaults from the dict is a very simple post-processing step that simply needs to happen at each level of the recursive transform. If `cattrs` would provide a direct pre-and-post conversion hook for unstructure_attrs_asdict, almost all of the code in that class would become unnecessary.  @Tinche would you be willing to accept a PR to add such a hook?

Note that my solution doesn't work for types constructed with factories, e.g. `attr.Factory(list)`. But for my use cases that actually works very well. If your use case required something different, you could modify `strip_attr_defaults` to take Factories into account.

**Comment by Tinche** [comment]
This is supported now using the new `GenConverter` and `omit_if_default`.
