### ISSUE TITLE
cattrs should use `dump` and `load` vs `dumps` and `loads`

### ISSUE THREAD

**Issue by hawkowl** [Tinche/cattrs#2]
`dumps` and `loads` in json (and other modules) stands for 'dump (to) string' or 'load (from) string', so the similar API doesn't copy across exactly. `json` in particular offers `dump` and `load` to read from a file, maybe `cattrs` should use these names because it is operating on types, not strings.

**Comment by wsanchez** [comment]
The `json` module names are terrible.

If these are meant to produce and consume JSON text, then something like `as_json_text` and `from_json_text` would be a lot clearer.

Names like `dump`/`load` or `structure`/`destructure` don't say anything about the serialization format, which only makes sense if the caller isn't supposed to care, but that seems unlikely.  In the `json` module's case, it's at least obvious that this will be JSON because it's the `json` module.  In `cattrs`' case, it's not.

I note the `README` says "Converts unstructured data into structured data" (and vice-versa).  I don't think that unstructured/structured is really correct terminology here… JSON text is not unstructured, though it's rather generic.

**Comment by wsanchez** [comment]
Actually I think you use "unstructured" to refer to non-JSON-serializable objects, not to JSON, so I was confused.  Also I was pretty new to this module, so "text" was wrong.

I think the distinction you want to make is JSON-serializable objects and other objects rather than structured and unstructured.  You refer to the former as "primitive objects" in the code, which makes sense to me, so maybe it's primitive vs. custom types.

So maybe `cattr.as_primitives` and `cattr.from_primitives` or something in that vain?

**Comment by Tinche** [comment]
I think I'm gonna go with just 'load' and 'dump'. The operations being performed are too complex to really express in something short enough to be a function name.

**Comment by glyph** [comment]
I really liked the idea for `structure` and `destructure`.  Perhaps `unstructure`, since it's converting it to "unstructured" data, not "destructured" data?

**Comment by Tinche** [comment]
Ok we're going with `structure` and `unstructure`.

**Comment by glyph** [comment]
🎉
